version: '3.9'

services:
  api:
    build: .
    ports:
      - "5000:80"
    depends_on:
      - db
    environment:
      - ConnectionStrings__DefaultConnection=server=db;port=3306;database=tarefasdb;user=root;password=123456;
  
  db:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: tarefasdb
    volumes:
      - dbdata:/var/lib/mysql

volumes:
  dbdata:
